### ISSUE TITLE
Difference between PhotonRoomProperties and RoomProtocolToken

### ISSUE THREAD

**Issue by donfour** [BoltEngine/Bolt-Sample#1]
I'm learning Bolt and I'm following the tutorial [here](https://doc.photonengine.com/en-us/bolt/current/in-depth/photon-cloud). When creating the room, the tutorial passes in a `RoomProtocolToken` to `SetServerInfo()`, while the sample code [here](https://github.com/BoltEngine/Bolt-Sample/blob/3ad4a36e5040cff00b9ca0463e738d54a10a33dd/PhotonCloud/demo_simple/Scripts/PhotonInit.cs#L107) uses `PhotonRoomProperties. AddRoomProperty()`. 

May I know what's the difference? Thank you!

**Comment by ramonmelo** [comment]
Hello @donfour,

Yes, there are some differences, but first, both are classes that implement the IProtocolToken interface and can be passed as extra data to certain operations on Bolt.

The `RoomProtocolToken` is just a simple Token that comes along with the Sample Package and exists just as an example, as so you can use the Token without creating it, in order to get a simple string passed by the server to the client, this can be like a map or a character to load.

On the other hand, `PhotonRoomProperties` is an internal Token implemented inside the Bolt SDK, that you can use to configure a room when using the `SetServerInfo()` function. By using this token you will be able to set the visibility of the room and/or some custom properties, so your clients will be able to know which type of game are you running (free-for-all or a team match for example), but these properties can be anything that is more related to your game.
